version: '3.7'

services:
  laravel:
    build:
      context: ./backend-app
    container_name: laravel_app
    ports:
      - "9000:9000"
    volumes:
      - ./backend-app:/var/www
    depends_on:
      - mysql
      - redis

  react:
    build:
      context: ./fe-knowledge
    container_name: react_app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: nhoncq
      MYSQL_USER: nhoncq
      MYSQL_PASSWORD: nhoncq
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  mysql_data:
